development:
  adapter: postgresql
  encoding: unicode
  database: signup_development
  host: localhost
  pool: 5
  username: michaellin
  password: jujruddo


test:
  adapter: postgresql
  encoding: unicode
  database: signup_test
  host: localhost
  pool: 5
  username: michaellin
  password: jujruddo
